environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - silberfishle
pipelines:
  silberfishle:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/pkissling/hello-spring-cloud.git
    stages:
      - build: # name of stage
          jobs:
            install: # name of the job
              tasks:
                - exec: # indicates type of task
                   command: /bin/sh
                   arguments:
                    - "-c"
                    - "chmod +x mvnw"
                    - "./mvnw clean install"