environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - silberfishle
pipelines:
  silberfishle:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/cicd-hackathon-stgt/gs-spring-boot.git
    stages:
      - build: # name of stage
          jobs:
            chmod: # name of the job
              tasks:
                - script: chmod +x mvnw
                - exec: # indicates type of task
                   command: /bin/sh
                   arguments:
                    - "chmod +x mvnw"